import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from 'axios';
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
    // Fetch data from Joomla API
    const res = await axios.get('https://joomla.nazarenko.de/index.php?option=com_nazarenkoapi&view=products&format=json');
    const products = res.data;
    console.log(products);
    // Pass data to the page via props
    return { props: { products } };
}


export default function Products({ products }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div>
                    <h1>PKW - Nachrüstfilter</h1>
                    <ul>
                        {products.map(product => (
                            <li key={product.product_id}>
                                <Link href={`/pkw-partikelfilter/nachruestfilter/${product.product_code}`}>{product.product_name}</Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </main>
        </>
    );
}
