import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from 'axios';
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });




export default function Products({ products }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div>
                    <h1>PKW</h1>
                    <div className={styles.title}>
                        <Link href="/pkw-partikelfilter/nachruestfilter">PKW Partikelfilter</Link>
                    </div>
                </div>
            </main>
        </>
    );
}
